// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Meme.proto

package protoapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meme struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemeId               string   `protobuf:"bytes,2,opt,name=meme_id,json=memeId,proto3" json:"meme_id,omitempty"`
	Public               string   `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Pictures             []string `protobuf:"bytes,5,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	Likes                int32    `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Reposts              int32    `protobuf:"varint,8,opt,name=reposts,proto3" json:"reposts,omitempty"`
	Views                int32    `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Comments             int32    `protobuf:"varint,10,opt,name=comments,proto3" json:"comments,omitempty"`
	Time                 int64    `protobuf:"varint,11,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meme) Reset()         { *m = Meme{} }
func (m *Meme) String() string { return proto.CompactTextString(m) }
func (*Meme) ProtoMessage()    {}
func (*Meme) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{0}
}

func (m *Meme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meme.Unmarshal(m, b)
}
func (m *Meme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meme.Marshal(b, m, deterministic)
}
func (m *Meme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meme.Merge(m, src)
}
func (m *Meme) XXX_Size() int {
	return xxx_messageInfo_Meme.Size(m)
}
func (m *Meme) XXX_DiscardUnknown() {
	xxx_messageInfo_Meme.DiscardUnknown(m)
}

var xxx_messageInfo_Meme proto.InternalMessageInfo

func (m *Meme) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Meme) GetMemeId() string {
	if m != nil {
		return m.MemeId
	}
	return ""
}

func (m *Meme) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *Meme) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Meme) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *Meme) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Meme) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Meme) GetReposts() int32 {
	if m != nil {
		return m.Reposts
	}
	return 0
}

func (m *Meme) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Meme) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *Meme) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetMemesRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesRequest) Reset()         { *m = GetMemesRequest{} }
func (m *GetMemesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemesRequest) ProtoMessage()    {}
func (*GetMemesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{1}
}

func (m *GetMemesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesRequest.Unmarshal(m, b)
}
func (m *GetMemesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesRequest.Marshal(b, m, deterministic)
}
func (m *GetMemesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesRequest.Merge(m, src)
}
func (m *GetMemesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemesRequest.Size(m)
}
func (m *GetMemesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesRequest proto.InternalMessageInfo

func (m *GetMemesRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type GetMemesResponse struct {
	Response             []*Meme  `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesResponse) Reset()         { *m = GetMemesResponse{} }
func (m *GetMemesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemesResponse) ProtoMessage()    {}
func (*GetMemesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{2}
}

func (m *GetMemesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesResponse.Unmarshal(m, b)
}
func (m *GetMemesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesResponse.Marshal(b, m, deterministic)
}
func (m *GetMemesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesResponse.Merge(m, src)
}
func (m *GetMemesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemesResponse.Size(m)
}
func (m *GetMemesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesResponse proto.InternalMessageInfo

func (m *GetMemesResponse) GetResponse() []*Meme {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Meme)(nil), "protoapi.Meme")
	proto.RegisterType((*GetMemesRequest)(nil), "protoapi.GetMemesRequest")
	proto.RegisterType((*GetMemesResponse)(nil), "protoapi.GetMemesResponse")
}

func init() { proto.RegisterFile("Meme.proto", fileDescriptor_fc8ad9bb7eaf31d1) }

var fileDescriptor_fc8ad9bb7eaf31d1 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x8a, 0xd4, 0x40,
	0x10, 0xc6, 0x49, 0x32, 0x93, 0xc9, 0x56, 0x74, 0x94, 0x52, 0xd6, 0x36, 0x7a, 0x08, 0x03, 0xc2,
	0xe0, 0x21, 0x81, 0xf5, 0x2e, 0x88, 0xff, 0xd8, 0x83, 0x22, 0x39, 0x7a, 0x91, 0xcc, 0x4c, 0xcd,
	0xd2, 0x98, 0x4e, 0xb7, 0xdd, 0x1d, 0xc5, 0xab, 0xaf, 0xe0, 0xc1, 0x67, 0xf1, 0x39, 0x7c, 0x05,
	0x1f, 0x44, 0xba, 0x32, 0x99, 0x11, 0x91, 0x3d, 0xa5, 0x7e, 0xf5, 0x7d, 0xfd, 0xa5, 0xba, 0x0b,
	0xe0, 0x0d, 0x29, 0xaa, 0x8c, 0xd5, 0x5e, 0x63, 0xc6, 0x9f, 0xd6, 0xc8, 0xe2, 0xe1, 0x95, 0xd6,
	0x57, 0x1d, 0xd5, 0xad, 0x91, 0x75, 0xdb, 0xf7, 0xda, 0xb7, 0x5e, 0xea, 0xde, 0x8d, 0xbe, 0xe2,
	0xc1, 0x41, 0x65, 0xda, 0x0c, 0xfb, 0xfa, 0xa5, 0x32, 0xfe, 0xeb, 0x28, 0xae, 0x7e, 0xc4, 0x30,
	0x0b, 0x99, 0xb8, 0x84, 0x58, 0xee, 0x44, 0x54, 0x46, 0xeb, 0x79, 0x13, 0xcb, 0x1d, 0xde, 0x83,
	0x85, 0x22, 0x45, 0x1f, 0xe4, 0x4e, 0xc4, 0x65, 0xb4, 0x3e, 0x6b, 0xd2, 0x80, 0x97, 0x3b, 0x3c,
	0x87, 0xd4, 0x0c, 0x9b, 0x4e, 0x6e, 0x45, 0x32, 0xf6, 0x47, 0xc2, 0x02, 0x32, 0xd3, 0xb5, 0x7e,
	0xaf, 0xad, 0x12, 0x33, 0x56, 0x8e, 0xcc, 0x9a, 0xdc, 0xfa, 0xc1, 0x92, 0x13, 0xf3, 0x32, 0x61,
	0xed, 0xc0, 0x58, 0x42, 0xfe, 0x82, 0xdc, 0xd6, 0x4a, 0x13, 0x86, 0x16, 0x29, 0x1f, 0xfd, 0xbb,
	0x85, 0x77, 0x61, 0xde, 0xc9, 0x8f, 0xe4, 0xc4, 0x82, 0xa7, 0x1b, 0x01, 0x05, 0x2c, 0x2c, 0x19,
	0xed, 0xbc, 0x13, 0x19, 0xf7, 0x27, 0x0c, 0xfe, 0xcf, 0x92, 0xbe, 0x38, 0x71, 0x36, 0xfa, 0x19,
	0xc2, 0x0c, 0x5b, 0xad, 0x14, 0xf5, 0xde, 0x09, 0x60, 0xe1, 0xc8, 0x88, 0x30, 0xf3, 0x52, 0x91,
	0xc8, 0xcb, 0x68, 0x9d, 0x34, 0x5c, 0xaf, 0x1e, 0xc1, 0xad, 0xd7, 0xe4, 0xc3, 0xdb, 0xb8, 0x86,
	0x3e, 0x0d, 0xe4, 0x7c, 0xb0, 0xed, 0xad, 0x56, 0xfc, 0x4a, 0x49, 0xc3, 0xf5, 0xea, 0x29, 0xdc,
	0x3e, 0xd9, 0x9c, 0xd1, 0xbd, 0x23, 0x7c, 0x0c, 0x99, 0x3d, 0xd4, 0x22, 0x2a, 0x93, 0x75, 0x7e,
	0xb1, 0xac, 0xa6, 0x65, 0x55, 0xc1, 0xda, 0x1c, 0xf5, 0x8b, 0x9f, 0x11, 0xe4, 0xcf, 0x75, 0xef,
	0x06, 0x45, 0xf6, 0xd9, 0xbb, 0x4b, 0x7c, 0x0b, 0xd9, 0x94, 0x87, 0xe7, 0xd5, 0xb8, 0xba, 0x6a,
	0x5a, 0x5d, 0xc5, 0xab, 0x2b, 0x8a, 0x53, 0xda, 0xbf, 0xff, 0x5e, 0x2d, 0xbf, 0xfd, 0xfa, 0xfd,
	0x3d, 0xce, 0x30, 0xad, 0x15, 0x67, 0xbc, 0x87, 0x1b, 0x93, 0xe7, 0x95, 0xd5, 0x0a, 0xef, 0xff,
	0xef, 0x2c, 0x5f, 0xef, 0xda, 0xd8, 0x3b, 0x1c, 0x7b, 0x13, 0xf3, 0x31, 0xb6, 0x0e, 0x77, 0xdf,
	0xa4, 0xec, 0x7f, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x66, 0xec, 0x1e, 0x0d, 0x96, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumerAPIClient is the client API for ConsumerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerAPIClient interface {
	GetMemes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMemesResponse, error)
	GetMemesFrom(ctx context.Context, in *GetMemesRequest, opts ...grpc.CallOption) (*GetMemesResponse, error)
}

type consumerAPIClient struct {
	cc *grpc.ClientConn
}

func NewConsumerAPIClient(cc *grpc.ClientConn) ConsumerAPIClient {
	return &consumerAPIClient{cc}
}

func (c *consumerAPIClient) GetMemes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.ConsumerAPI/GetMemes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerAPIClient) GetMemesFrom(ctx context.Context, in *GetMemesRequest, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.ConsumerAPI/GetMemesFrom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerAPIServer is the server API for ConsumerAPI service.
type ConsumerAPIServer interface {
	GetMemes(context.Context, *empty.Empty) (*GetMemesResponse, error)
	GetMemesFrom(context.Context, *GetMemesRequest) (*GetMemesResponse, error)
}

func RegisterConsumerAPIServer(s *grpc.Server, srv ConsumerAPIServer) {
	s.RegisterService(&_ConsumerAPI_serviceDesc, srv)
}

func _ConsumerAPI_GetMemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerAPIServer).GetMemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.ConsumerAPI/GetMemes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerAPIServer).GetMemes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerAPI_GetMemesFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerAPIServer).GetMemesFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.ConsumerAPI/GetMemesFrom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerAPIServer).GetMemesFrom(ctx, req.(*GetMemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsumerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoapi.ConsumerAPI",
	HandlerType: (*ConsumerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMemes",
			Handler:    _ConsumerAPI_GetMemes_Handler,
		},
		{
			MethodName: "GetMemesFrom",
			Handler:    _ConsumerAPI_GetMemesFrom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Meme.proto",
}
