// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Meme.proto

package protoapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meme struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MemeId               string   `protobuf:"bytes,2,opt,name=meme_id,json=memeId,proto3" json:"meme_id,omitempty"`
	Public               string   `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Pictures             []string `protobuf:"bytes,5,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Likes                int32    `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Reposts              int32    `protobuf:"varint,8,opt,name=reposts,proto3" json:"reposts,omitempty"`
	Views                int32    `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Comments             int32    `protobuf:"varint,10,opt,name=comments,proto3" json:"comments,omitempty"`
	Time                 int64    `protobuf:"varint,11,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meme) Reset()         { *m = Meme{} }
func (m *Meme) String() string { return proto.CompactTextString(m) }
func (*Meme) ProtoMessage()    {}
func (*Meme) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{0}
}

func (m *Meme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meme.Unmarshal(m, b)
}
func (m *Meme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meme.Marshal(b, m, deterministic)
}
func (m *Meme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meme.Merge(m, src)
}
func (m *Meme) XXX_Size() int {
	return xxx_messageInfo_Meme.Size(m)
}
func (m *Meme) XXX_DiscardUnknown() {
	xxx_messageInfo_Meme.DiscardUnknown(m)
}

var xxx_messageInfo_Meme proto.InternalMessageInfo

func (m *Meme) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Meme) GetMemeId() string {
	if m != nil {
		return m.MemeId
	}
	return ""
}

func (m *Meme) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *Meme) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Meme) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *Meme) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Meme) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Meme) GetReposts() int32 {
	if m != nil {
		return m.Reposts
	}
	return 0
}

func (m *Meme) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Meme) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *Meme) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetMemesRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesRequest) Reset()         { *m = GetMemesRequest{} }
func (m *GetMemesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemesRequest) ProtoMessage()    {}
func (*GetMemesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{1}
}

func (m *GetMemesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesRequest.Unmarshal(m, b)
}
func (m *GetMemesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesRequest.Marshal(b, m, deterministic)
}
func (m *GetMemesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesRequest.Merge(m, src)
}
func (m *GetMemesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemesRequest.Size(m)
}
func (m *GetMemesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesRequest proto.InternalMessageInfo

func (m *GetMemesRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type GetMemesResponse struct {
	Response             []*Meme  `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesResponse) Reset()         { *m = GetMemesResponse{} }
func (m *GetMemesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemesResponse) ProtoMessage()    {}
func (*GetMemesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{2}
}

func (m *GetMemesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesResponse.Unmarshal(m, b)
}
func (m *GetMemesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesResponse.Marshal(b, m, deterministic)
}
func (m *GetMemesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesResponse.Merge(m, src)
}
func (m *GetMemesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemesResponse.Size(m)
}
func (m *GetMemesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesResponse proto.InternalMessageInfo

func (m *GetMemesResponse) GetResponse() []*Meme {
	if m != nil {
		return m.Response
	}
	return nil
}

type AddMemeRequest struct {
	Meme                 *Meme    `protobuf:"bytes,1,opt,name=meme,proto3" json:"meme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemeRequest) Reset()         { *m = AddMemeRequest{} }
func (m *AddMemeRequest) String() string { return proto.CompactTextString(m) }
func (*AddMemeRequest) ProtoMessage()    {}
func (*AddMemeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{3}
}

func (m *AddMemeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemeRequest.Unmarshal(m, b)
}
func (m *AddMemeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemeRequest.Marshal(b, m, deterministic)
}
func (m *AddMemeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemeRequest.Merge(m, src)
}
func (m *AddMemeRequest) XXX_Size() int {
	return xxx_messageInfo_AddMemeRequest.Size(m)
}
func (m *AddMemeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemeRequest proto.InternalMessageInfo

func (m *AddMemeRequest) GetMeme() *Meme {
	if m != nil {
		return m.Meme
	}
	return nil
}

type MakeActionRequest struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BtnId                int32    `protobuf:"varint,5,opt,name=btn_id,json=btnId,proto3" json:"btn_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeActionRequest) Reset()         { *m = MakeActionRequest{} }
func (m *MakeActionRequest) String() string { return proto.CompactTextString(m) }
func (*MakeActionRequest) ProtoMessage()    {}
func (*MakeActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{4}
}

func (m *MakeActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeActionRequest.Unmarshal(m, b)
}
func (m *MakeActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeActionRequest.Marshal(b, m, deterministic)
}
func (m *MakeActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeActionRequest.Merge(m, src)
}
func (m *MakeActionRequest) XXX_Size() int {
	return xxx_messageInfo_MakeActionRequest.Size(m)
}
func (m *MakeActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeActionRequest proto.InternalMessageInfo

func (m *MakeActionRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *MakeActionRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *MakeActionRequest) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MakeActionRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MakeActionRequest) GetBtnId() int32 {
	if m != nil {
		return m.BtnId
	}
	return 0
}

type IsMemeExistsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Public               string   `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	Platfrom             string   `protobuf:"bytes,3,opt,name=platfrom,proto3" json:"platfrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsMemeExistsRequest) Reset()         { *m = IsMemeExistsRequest{} }
func (m *IsMemeExistsRequest) String() string { return proto.CompactTextString(m) }
func (*IsMemeExistsRequest) ProtoMessage()    {}
func (*IsMemeExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{5}
}

func (m *IsMemeExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsMemeExistsRequest.Unmarshal(m, b)
}
func (m *IsMemeExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsMemeExistsRequest.Marshal(b, m, deterministic)
}
func (m *IsMemeExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsMemeExistsRequest.Merge(m, src)
}
func (m *IsMemeExistsRequest) XXX_Size() int {
	return xxx_messageInfo_IsMemeExistsRequest.Size(m)
}
func (m *IsMemeExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsMemeExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsMemeExistsRequest proto.InternalMessageInfo

func (m *IsMemeExistsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IsMemeExistsRequest) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *IsMemeExistsRequest) GetPlatfrom() string {
	if m != nil {
		return m.Platfrom
	}
	return ""
}

type IsMemeExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsMemeExistsResponse) Reset()         { *m = IsMemeExistsResponse{} }
func (m *IsMemeExistsResponse) String() string { return proto.CompactTextString(m) }
func (*IsMemeExistsResponse) ProtoMessage()    {}
func (*IsMemeExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{6}
}

func (m *IsMemeExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsMemeExistsResponse.Unmarshal(m, b)
}
func (m *IsMemeExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsMemeExistsResponse.Marshal(b, m, deterministic)
}
func (m *IsMemeExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsMemeExistsResponse.Merge(m, src)
}
func (m *IsMemeExistsResponse) XXX_Size() int {
	return xxx_messageInfo_IsMemeExistsResponse.Size(m)
}
func (m *IsMemeExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsMemeExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsMemeExistsResponse proto.InternalMessageInfo

func (m *IsMemeExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type GetMemeByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemeByIdRequest) Reset()         { *m = GetMemeByIdRequest{} }
func (m *GetMemeByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemeByIdRequest) ProtoMessage()    {}
func (*GetMemeByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{7}
}

func (m *GetMemeByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemeByIdRequest.Unmarshal(m, b)
}
func (m *GetMemeByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemeByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetMemeByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemeByIdRequest.Merge(m, src)
}
func (m *GetMemeByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemeByIdRequest.Size(m)
}
func (m *GetMemeByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemeByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemeByIdRequest proto.InternalMessageInfo

func (m *GetMemeByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMemeByIdResponse struct {
	Meme                 *Meme    `protobuf:"bytes,1,opt,name=meme,proto3" json:"meme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemeByIdResponse) Reset()         { *m = GetMemeByIdResponse{} }
func (m *GetMemeByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemeByIdResponse) ProtoMessage()    {}
func (*GetMemeByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{8}
}

func (m *GetMemeByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemeByIdResponse.Unmarshal(m, b)
}
func (m *GetMemeByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemeByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetMemeByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemeByIdResponse.Merge(m, src)
}
func (m *GetMemeByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemeByIdResponse.Size(m)
}
func (m *GetMemeByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemeByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemeByIdResponse proto.InternalMessageInfo

func (m *GetMemeByIdResponse) GetMeme() *Meme {
	if m != nil {
		return m.Meme
	}
	return nil
}

type MarkMemeShownRequest struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MemeId               int32    `protobuf:"varint,3,opt,name=meme_id,json=memeId,proto3" json:"meme_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkMemeShownRequest) Reset()         { *m = MarkMemeShownRequest{} }
func (m *MarkMemeShownRequest) String() string { return proto.CompactTextString(m) }
func (*MarkMemeShownRequest) ProtoMessage()    {}
func (*MarkMemeShownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{9}
}

func (m *MarkMemeShownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkMemeShownRequest.Unmarshal(m, b)
}
func (m *MarkMemeShownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkMemeShownRequest.Marshal(b, m, deterministic)
}
func (m *MarkMemeShownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkMemeShownRequest.Merge(m, src)
}
func (m *MarkMemeShownRequest) XXX_Size() int {
	return xxx_messageInfo_MarkMemeShownRequest.Size(m)
}
func (m *MarkMemeShownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkMemeShownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkMemeShownRequest proto.InternalMessageInfo

func (m *MarkMemeShownRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *MarkMemeShownRequest) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MarkMemeShownRequest) GetMemeId() int32 {
	if m != nil {
		return m.MemeId
	}
	return 0
}

type GetMemesStorageRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesStorageRequest) Reset()         { *m = GetMemesStorageRequest{} }
func (m *GetMemesStorageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemesStorageRequest) ProtoMessage()    {}
func (*GetMemesStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{10}
}

func (m *GetMemesStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesStorageRequest.Unmarshal(m, b)
}
func (m *GetMemesStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesStorageRequest.Marshal(b, m, deterministic)
}
func (m *GetMemesStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesStorageRequest.Merge(m, src)
}
func (m *GetMemesStorageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemesStorageRequest.Size(m)
}
func (m *GetMemesStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesStorageRequest proto.InternalMessageInfo

func (m *GetMemesStorageRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type GetMemesStorageUnshownRequest struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemesStorageUnshownRequest) Reset()         { *m = GetMemesStorageUnshownRequest{} }
func (m *GetMemesStorageUnshownRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemesStorageUnshownRequest) ProtoMessage()    {}
func (*GetMemesStorageUnshownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{11}
}

func (m *GetMemesStorageUnshownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemesStorageUnshownRequest.Unmarshal(m, b)
}
func (m *GetMemesStorageUnshownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemesStorageUnshownRequest.Marshal(b, m, deterministic)
}
func (m *GetMemesStorageUnshownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemesStorageUnshownRequest.Merge(m, src)
}
func (m *GetMemesStorageUnshownRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemesStorageUnshownRequest.Size(m)
}
func (m *GetMemesStorageUnshownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemesStorageUnshownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemesStorageUnshownRequest proto.InternalMessageInfo

func (m *GetMemesStorageUnshownRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *GetMemesStorageUnshownRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

type ShownMemeInfo struct {
	MemeId               int32    `protobuf:"varint,1,opt,name=meme_id,json=memeId,proto3" json:"meme_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Likes                int32    `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes             int32    `protobuf:"varint,4,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShownMemeInfo) Reset()         { *m = ShownMemeInfo{} }
func (m *ShownMemeInfo) String() string { return proto.CompactTextString(m) }
func (*ShownMemeInfo) ProtoMessage()    {}
func (*ShownMemeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{12}
}

func (m *ShownMemeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShownMemeInfo.Unmarshal(m, b)
}
func (m *ShownMemeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShownMemeInfo.Marshal(b, m, deterministic)
}
func (m *ShownMemeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShownMemeInfo.Merge(m, src)
}
func (m *ShownMemeInfo) XXX_Size() int {
	return xxx_messageInfo_ShownMemeInfo.Size(m)
}
func (m *ShownMemeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShownMemeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShownMemeInfo proto.InternalMessageInfo

func (m *ShownMemeInfo) GetMemeId() int32 {
	if m != nil {
		return m.MemeId
	}
	return 0
}

func (m *ShownMemeInfo) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ShownMemeInfo) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *ShownMemeInfo) GetDislikes() int32 {
	if m != nil {
		return m.Dislikes
	}
	return 0
}

type GetShownMemesInfoRequest struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShownMemesInfoRequest) Reset()         { *m = GetShownMemesInfoRequest{} }
func (m *GetShownMemesInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetShownMemesInfoRequest) ProtoMessage()    {}
func (*GetShownMemesInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{13}
}

func (m *GetShownMemesInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShownMemesInfoRequest.Unmarshal(m, b)
}
func (m *GetShownMemesInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShownMemesInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetShownMemesInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShownMemesInfoRequest.Merge(m, src)
}
func (m *GetShownMemesInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetShownMemesInfoRequest.Size(m)
}
func (m *GetShownMemesInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShownMemesInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShownMemesInfoRequest proto.InternalMessageInfo

func (m *GetShownMemesInfoRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

type GetShownMemesInfoResponse struct {
	Response             []*ShownMemeInfo `protobuf:"bytes,1,rep,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetShownMemesInfoResponse) Reset()         { *m = GetShownMemesInfoResponse{} }
func (m *GetShownMemesInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetShownMemesInfoResponse) ProtoMessage()    {}
func (*GetShownMemesInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{14}
}

func (m *GetShownMemesInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShownMemesInfoResponse.Unmarshal(m, b)
}
func (m *GetShownMemesInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShownMemesInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetShownMemesInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShownMemesInfoResponse.Merge(m, src)
}
func (m *GetShownMemesInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetShownMemesInfoResponse.Size(m)
}
func (m *GetShownMemesInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShownMemesInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShownMemesInfoResponse proto.InternalMessageInfo

func (m *GetShownMemesInfoResponse) GetResponse() []*ShownMemeInfo {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetMemeInfoRequest struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemeInfoRequest) Reset()         { *m = GetMemeInfoRequest{} }
func (m *GetMemeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemeInfoRequest) ProtoMessage()    {}
func (*GetMemeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{15}
}

func (m *GetMemeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemeInfoRequest.Unmarshal(m, b)
}
func (m *GetMemeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemeInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetMemeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemeInfoRequest.Merge(m, src)
}
func (m *GetMemeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemeInfoRequest.Size(m)
}
func (m *GetMemeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemeInfoRequest proto.InternalMessageInfo

func (m *GetMemeInfoRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *GetMemeInfoRequest) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *GetMemeInfoRequest) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type GetMemeInfoResponse struct {
	Reactions            map[int32]int32 `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetMemeInfoResponse) Reset()         { *m = GetMemeInfoResponse{} }
func (m *GetMemeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemeInfoResponse) ProtoMessage()    {}
func (*GetMemeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc8ad9bb7eaf31d1, []int{16}
}

func (m *GetMemeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemeInfoResponse.Unmarshal(m, b)
}
func (m *GetMemeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemeInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetMemeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemeInfoResponse.Merge(m, src)
}
func (m *GetMemeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemeInfoResponse.Size(m)
}
func (m *GetMemeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemeInfoResponse proto.InternalMessageInfo

func (m *GetMemeInfoResponse) GetReactions() map[int32]int32 {
	if m != nil {
		return m.Reactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Meme)(nil), "protoapi.Meme")
	proto.RegisterType((*GetMemesRequest)(nil), "protoapi.GetMemesRequest")
	proto.RegisterType((*GetMemesResponse)(nil), "protoapi.GetMemesResponse")
	proto.RegisterType((*AddMemeRequest)(nil), "protoapi.AddMemeRequest")
	proto.RegisterType((*MakeActionRequest)(nil), "protoapi.MakeActionRequest")
	proto.RegisterType((*IsMemeExistsRequest)(nil), "protoapi.IsMemeExistsRequest")
	proto.RegisterType((*IsMemeExistsResponse)(nil), "protoapi.IsMemeExistsResponse")
	proto.RegisterType((*GetMemeByIdRequest)(nil), "protoapi.GetMemeByIdRequest")
	proto.RegisterType((*GetMemeByIdResponse)(nil), "protoapi.GetMemeByIdResponse")
	proto.RegisterType((*MarkMemeShownRequest)(nil), "protoapi.MarkMemeShownRequest")
	proto.RegisterType((*GetMemesStorageRequest)(nil), "protoapi.GetMemesStorageRequest")
	proto.RegisterType((*GetMemesStorageUnshownRequest)(nil), "protoapi.GetMemesStorageUnshownRequest")
	proto.RegisterType((*ShownMemeInfo)(nil), "protoapi.ShownMemeInfo")
	proto.RegisterType((*GetShownMemesInfoRequest)(nil), "protoapi.GetShownMemesInfoRequest")
	proto.RegisterType((*GetShownMemesInfoResponse)(nil), "protoapi.GetShownMemesInfoResponse")
	proto.RegisterType((*GetMemeInfoRequest)(nil), "protoapi.GetMemeInfoRequest")
	proto.RegisterType((*GetMemeInfoResponse)(nil), "protoapi.GetMemeInfoResponse")
	proto.RegisterMapType((map[int32]int32)(nil), "protoapi.GetMemeInfoResponse.ReactionsEntry")
}

func init() { proto.RegisterFile("Meme.proto", fileDescriptor_fc8ad9bb7eaf31d1) }

var fileDescriptor_fc8ad9bb7eaf31d1 = []byte{
	// 1008 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xe3, 0x54,
	0x10, 0x96, 0xe3, 0xc6, 0x49, 0x26, 0x4d, 0xda, 0x4e, 0xdb, 0xd4, 0xf5, 0xb6, 0xab, 0xe8, 0x00,
	0xa2, 0x42, 0xab, 0x44, 0x6a, 0xb9, 0x00, 0x84, 0x90, 0x0a, 0x2a, 0x2b, 0xaf, 0x28, 0x5a, 0x79,
	0x05, 0x02, 0x2e, 0x58, 0x9c, 0xf8, 0x34, 0xb5, 0x1a, 0xdb, 0x59, 0x1f, 0x87, 0x52, 0xa1, 0xbd,
	0xe1, 0x15, 0xb8, 0xd8, 0x4b, 0x9e, 0x83, 0xe7, 0xe0, 0x15, 0x78, 0x0a, 0xae, 0xd0, 0x19, 0x1f,
	0xff, 0x35, 0x71, 0x81, 0x0b, 0xae, 0x92, 0x39, 0x33, 0x67, 0xbe, 0x39, 0x33, 0xdf, 0x7c, 0x06,
	0xb8, 0xe4, 0x01, 0x1f, 0x2d, 0xe2, 0x28, 0x89, 0xb0, 0x4d, 0x3f, 0xee, 0xc2, 0xb7, 0x8e, 0x66,
	0x51, 0x34, 0x9b, 0xf3, 0xb1, 0xbb, 0xf0, 0xc7, 0x6e, 0x18, 0x46, 0x89, 0x9b, 0xf8, 0x51, 0x28,
	0xd2, 0x38, 0xeb, 0x91, 0xf2, 0x92, 0x35, 0x59, 0x5e, 0x8d, 0x2f, 0x82, 0x45, 0x72, 0x97, 0x3a,
	0xd9, 0x9b, 0x06, 0x6c, 0xc8, 0x9c, 0xd8, 0x87, 0x86, 0xef, 0x99, 0xda, 0x50, 0x3b, 0x69, 0x3a,
	0x0d, 0xdf, 0xc3, 0x03, 0x68, 0x05, 0x3c, 0xe0, 0x2f, 0x7d, 0xcf, 0x6c, 0x0c, 0xb5, 0x93, 0x8e,
	0x63, 0x48, 0xd3, 0xf6, 0x70, 0x00, 0xc6, 0x62, 0x39, 0x99, 0xfb, 0x53, 0x53, 0x4f, 0xcf, 0x53,
	0x0b, 0x2d, 0x68, 0x2f, 0xe6, 0x6e, 0x72, 0x15, 0xc5, 0x81, 0xb9, 0x41, 0x9e, 0xdc, 0x26, 0x9f,
	0x3f, 0x4d, 0x96, 0x31, 0x17, 0x66, 0x73, 0xa8, 0x93, 0x4f, 0xd9, 0x38, 0x84, 0xae, 0xc7, 0xc5,
	0x34, 0xf6, 0x17, 0xb2, 0x68, 0xd3, 0xa0, 0xab, 0xe5, 0x23, 0xdc, 0x83, 0xe6, 0xdc, 0xbf, 0xe1,
	0xc2, 0x6c, 0x51, 0x75, 0xa9, 0x81, 0x26, 0xb4, 0x62, 0xbe, 0x88, 0x44, 0x22, 0xcc, 0x36, 0x9d,
	0x67, 0xa6, 0x8c, 0xff, 0xd1, 0xe7, 0xb7, 0xc2, 0xec, 0xa4, 0xf1, 0x64, 0xc8, 0x1a, 0xa6, 0x51,
	0x10, 0xf0, 0x30, 0x11, 0x26, 0x90, 0x23, 0xb7, 0x11, 0x61, 0x23, 0xf1, 0x03, 0x6e, 0x76, 0x87,
	0xda, 0x89, 0xee, 0xd0, 0x7f, 0xf6, 0x0e, 0x6c, 0x3d, 0xe5, 0x89, 0xec, 0x8d, 0x70, 0xf8, 0xab,
	0x25, 0x17, 0x89, 0x0c, 0xbb, 0x8a, 0xa3, 0x80, 0xba, 0xa4, 0x3b, 0xf4, 0x9f, 0x7d, 0x02, 0xdb,
	0x45, 0x98, 0x58, 0x44, 0xa1, 0xe0, 0xf8, 0x1e, 0xb4, 0x63, 0xf5, 0xdf, 0xd4, 0x86, 0xfa, 0x49,
	0xf7, 0xb4, 0x3f, 0xca, 0x86, 0x35, 0x92, 0xa1, 0x4e, 0xee, 0x67, 0xef, 0x43, 0xff, 0xdc, 0xf3,
	0xe8, 0x50, 0xa1, 0x30, 0xd8, 0x90, 0xad, 0x26, 0x94, 0xd5, 0x9b, 0xe4, 0x63, 0x6f, 0x34, 0xd8,
	0xb9, 0x74, 0x6f, 0xf8, 0xf9, 0x54, 0x76, 0x28, 0xbb, 0x59, 0x1e, 0x81, 0x76, 0x6f, 0x04, 0x07,
	0xd0, 0x9a, 0x5e, 0xbb, 0x49, 0x36, 0x4f, 0xdd, 0x31, 0xa4, 0x69, 0x7b, 0x78, 0x0c, 0x10, 0x70,
	0x21, 0xdc, 0x19, 0xcd, 0x5a, 0xa7, 0xce, 0x74, 0xd4, 0x89, 0x4d, 0x3c, 0x58, 0x0a, 0x1e, 0x4b,
	0xdf, 0x06, 0xf9, 0x0c, 0x69, 0xda, 0x1e, 0xee, 0x83, 0x31, 0x49, 0x42, 0x79, 0xde, 0x4c, 0xdb,
	0x3c, 0x49, 0x42, 0xdb, 0x63, 0xdf, 0xc2, 0xae, 0x2d, 0x64, 0xa5, 0x17, 0x3f, 0xf9, 0x22, 0xc9,
	0x5b, 0x57, 0xd0, 0xab, 0x43, 0xf4, 0x2a, 0x58, 0xd4, 0x58, 0xcb, 0x22, 0xd9, 0x66, 0xbd, 0xf4,
	0x04, 0xd9, 0xea, 0x11, 0xec, 0x55, 0x53, 0xab, 0x76, 0x0f, 0xc0, 0xe0, 0x74, 0x42, 0xf9, 0xdb,
	0x8e, 0xb2, 0xd8, 0xdb, 0x80, 0x6a, 0x34, 0x9f, 0xde, 0xd9, 0xde, 0x6a, 0x25, 0x44, 0x74, 0xf6,
	0x21, 0xec, 0x56, 0xa2, 0x54, 0xd2, 0x7f, 0x33, 0x85, 0x97, 0xb0, 0x77, 0xe9, 0xc6, 0x37, 0xf2,
	0xe4, 0xc5, 0x75, 0x74, 0x9b, 0xcf, 0xa1, 0xd4, 0x6b, 0xad, 0xd2, 0xeb, 0x7d, 0x30, 0x02, 0x31,
	0xcb, 0x66, 0xd0, 0x74, 0x9a, 0x81, 0x98, 0xd9, 0x95, 0x5d, 0x4b, 0xfb, 0xaf, 0x76, 0x8d, 0x3d,
	0x81, 0x41, 0x46, 0xae, 0x17, 0x49, 0x14, 0xbb, 0x33, 0xfe, 0x10, 0x15, 0xbf, 0x80, 0xe3, 0x7b,
	0xd1, 0x5f, 0x85, 0xa2, 0x5c, 0xd7, 0x9a, 0x4b, 0xb5, 0xbc, 0x60, 0xaf, 0xa0, 0x47, 0x8f, 0x92,
	0xf9, 0xec, 0xf0, 0x2a, 0x2a, 0x57, 0xa9, 0x95, 0xab, 0xac, 0x7b, 0x55, 0xbe, 0xb6, 0x7a, 0x79,
	0x6d, 0x2d, 0x68, 0x7b, 0xbe, 0x48, 0x1d, 0x29, 0xa1, 0x72, 0x9b, 0x9d, 0x81, 0xf9, 0x94, 0x27,
	0x39, 0xaa, 0x90, 0xb0, 0xff, 0xd4, 0x53, 0xf6, 0x1c, 0x0e, 0xd7, 0x5c, 0x52, 0x53, 0x3c, 0x83,
	0xb6, 0x53, 0xdd, 0xc4, 0x83, 0x62, 0x92, 0x95, 0xe7, 0x39, 0x79, 0x20, 0xbb, 0xce, 0x79, 0x53,
	0x2e, 0xe0, 0x7f, 0x58, 0x2e, 0xf6, 0x9b, 0x96, 0x93, 0xaf, 0x52, 0xf6, 0x33, 0xe8, 0xc4, 0xdc,
	0xa5, 0xdd, 0x16, 0xaa, 0xee, 0x27, 0x45, 0xdd, 0x6b, 0x6e, 0x8c, 0x9c, 0x2c, 0xfc, 0x22, 0x4c,
	0xe2, 0x3b, 0xa7, 0xb8, 0x6e, 0x7d, 0x0c, 0xfd, 0xaa, 0x13, 0xb7, 0x41, 0xbf, 0xe1, 0x77, 0x6a,
	0x88, 0xf2, 0x2f, 0x29, 0xa6, 0x3b, 0x5f, 0xf2, 0x6c, 0x80, 0x64, 0x7c, 0xd4, 0xf8, 0x40, 0x3b,
	0xfd, 0x5d, 0x83, 0xee, 0x67, 0x51, 0x28, 0x96, 0x01, 0x8f, 0xcf, 0x9f, 0xdb, 0xf8, 0x25, 0xb4,
	0x33, 0x8e, 0xe1, 0x60, 0x94, 0x7e, 0x59, 0x46, 0xd9, 0x97, 0x65, 0x44, 0x5f, 0x16, 0xcb, 0x5a,
	0x29, 0x35, 0xdf, 0x55, 0xd6, 0xff, 0xe5, 0x8f, 0x3f, 0x7f, 0x6d, 0xb4, 0xd1, 0x18, 0x07, 0x94,
	0xe3, 0x3b, 0xd8, 0xcc, 0x62, 0x3e, 0x97, 0x74, 0x3c, 0x5c, 0x77, 0x97, 0x06, 0xf0, 0x60, 0xda,
	0x5d, 0x4a, 0xdb, 0xc3, 0x6e, 0x9a, 0x76, 0x2c, 0xa9, 0x7d, 0xfa, 0x97, 0x01, 0x2d, 0xb5, 0x08,
	0xf8, 0x0c, 0x5a, 0x4a, 0x66, 0xd1, 0x2c, 0xf2, 0x54, 0x95, 0xd7, 0xaa, 0x79, 0x10, 0xeb, 0x51,
	0xf6, 0x96, 0xd5, 0xa4, 0xec, 0xf8, 0x35, 0x40, 0xa1, 0xbd, 0xf8, 0xa8, 0x24, 0x0d, 0xf7, 0x15,
	0xb9, 0x36, 0xa3, 0xaa, 0x97, 0x75, 0xc7, 0x41, 0x91, 0x69, 0x0a, 0x9b, 0x65, 0x7d, 0xc3, 0xe3,
	0x22, 0xf3, 0x1a, 0x49, 0xb5, 0x1e, 0xd7, 0xb9, 0x55, 0x4f, 0xf6, 0x08, 0xa3, 0x8f, 0x9b, 0x54,
	0xf5, 0x38, 0x15, 0x45, 0xfc, 0x1e, 0xba, 0x25, 0xb9, 0xc3, 0xa3, 0x95, 0xa6, 0x96, 0xb4, 0xd2,
	0x3a, 0xae, 0xf1, 0x2a, 0x04, 0x24, 0x84, 0x4d, 0x84, 0x14, 0xe1, 0x67, 0xdf, 0x7b, 0x8d, 0x3f,
	0x40, 0xaf, 0xa2, 0x89, 0xf8, 0xb8, 0xdc, 0x9f, 0x55, 0xb1, 0xac, 0x6d, 0xd1, 0x01, 0x25, 0xdf,
	0x39, 0xdd, 0x52, 0xc9, 0x95, 0xf6, 0xbc, 0xc6, 0x6f, 0x4a, 0x14, 0x1c, 0xae, 0x72, 0xa2, 0x2a,
	0x94, 0xff, 0x89, 0x8c, 0x61, 0xf1, 0xc9, 0x57, 0xca, 0x89, 0xef, 0xd6, 0x02, 0x54, 0xb5, 0xf5,
	0x41, 0x9c, 0x01, 0xe1, 0x6c, 0x63, 0x5f, 0xb1, 0x73, 0xa9, 0x92, 0xdf, 0xc2, 0xce, 0x8a, 0x74,
	0x21, 0xab, 0x24, 0x5a, 0x2b, 0x86, 0xd6, 0x5b, 0x0f, 0xc6, 0x28, 0xd4, 0x43, 0x42, 0xdd, 0xc5,
	0x1d, 0x85, 0x4a, 0x98, 0x63, 0x5f, 0x62, 0xb8, 0x39, 0x09, 0x08, 0xf2, 0xa8, 0x46, 0x5b, 0xea,
	0x48, 0x50, 0x81, 0xd9, 0x27, 0x98, 0x2d, 0xec, 0xa5, 0x73, 0xf2, 0x3d, 0x82, 0x98, 0x18, 0x74,
	0xe9, 0xec, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x53, 0x55, 0x6b, 0xb2, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumerAPIClient is the client API for ConsumerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerAPIClient interface {
	GetMemes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMemesResponse, error)
	GetMemesFrom(ctx context.Context, in *GetMemesRequest, opts ...grpc.CallOption) (*GetMemesResponse, error)
}

type consumerAPIClient struct {
	cc *grpc.ClientConn
}

func NewConsumerAPIClient(cc *grpc.ClientConn) ConsumerAPIClient {
	return &consumerAPIClient{cc}
}

func (c *consumerAPIClient) GetMemes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.ConsumerAPI/GetMemes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerAPIClient) GetMemesFrom(ctx context.Context, in *GetMemesRequest, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.ConsumerAPI/GetMemesFrom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerAPIServer is the server API for ConsumerAPI service.
type ConsumerAPIServer interface {
	GetMemes(context.Context, *empty.Empty) (*GetMemesResponse, error)
	GetMemesFrom(context.Context, *GetMemesRequest) (*GetMemesResponse, error)
}

func RegisterConsumerAPIServer(s *grpc.Server, srv ConsumerAPIServer) {
	s.RegisterService(&_ConsumerAPI_serviceDesc, srv)
}

func _ConsumerAPI_GetMemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerAPIServer).GetMemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.ConsumerAPI/GetMemes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerAPIServer).GetMemes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerAPI_GetMemesFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerAPIServer).GetMemesFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.ConsumerAPI/GetMemesFrom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerAPIServer).GetMemesFrom(ctx, req.(*GetMemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsumerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoapi.ConsumerAPI",
	HandlerType: (*ConsumerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMemes",
			Handler:    _ConsumerAPI_GetMemes_Handler,
		},
		{
			MethodName: "GetMemesFrom",
			Handler:    _ConsumerAPI_GetMemesFrom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Meme.proto",
}

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	AddMeme(ctx context.Context, in *AddMemeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	MakeAction(ctx context.Context, in *MakeActionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	IsMemeExists(ctx context.Context, in *IsMemeExistsRequest, opts ...grpc.CallOption) (*IsMemeExistsResponse, error)
	GetMemeById(ctx context.Context, in *GetMemeByIdRequest, opts ...grpc.CallOption) (*GetMemeByIdResponse, error)
	MarkMemeShown(ctx context.Context, in *MarkMemeShownRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMemes(ctx context.Context, in *GetMemesStorageRequest, opts ...grpc.CallOption) (*GetMemesResponse, error)
	GetMemesUnshown(ctx context.Context, in *GetMemesStorageUnshownRequest, opts ...grpc.CallOption) (*GetMemesResponse, error)
	GetShownMemesInfo(ctx context.Context, in *GetShownMemesInfoRequest, opts ...grpc.CallOption) (*GetShownMemesInfoResponse, error)
	GetMemeInfo(ctx context.Context, in *GetMemeInfoRequest, opts ...grpc.CallOption) (*GetMemeInfoResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) AddMeme(ctx context.Context, in *AddMemeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/AddMeme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) MakeAction(ctx context.Context, in *MakeActionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/MakeAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) IsMemeExists(ctx context.Context, in *IsMemeExistsRequest, opts ...grpc.CallOption) (*IsMemeExistsResponse, error) {
	out := new(IsMemeExistsResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/IsMemeExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetMemeById(ctx context.Context, in *GetMemeByIdRequest, opts ...grpc.CallOption) (*GetMemeByIdResponse, error) {
	out := new(GetMemeByIdResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/GetMemeById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) MarkMemeShown(ctx context.Context, in *MarkMemeShownRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/MarkMemeShown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetMemes(ctx context.Context, in *GetMemesStorageRequest, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/GetMemes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetMemesUnshown(ctx context.Context, in *GetMemesStorageUnshownRequest, opts ...grpc.CallOption) (*GetMemesResponse, error) {
	out := new(GetMemesResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/GetMemesUnshown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetShownMemesInfo(ctx context.Context, in *GetShownMemesInfoRequest, opts ...grpc.CallOption) (*GetShownMemesInfoResponse, error) {
	out := new(GetShownMemesInfoResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/GetShownMemesInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetMemeInfo(ctx context.Context, in *GetMemeInfoRequest, opts ...grpc.CallOption) (*GetMemeInfoResponse, error) {
	out := new(GetMemeInfoResponse)
	err := c.cc.Invoke(ctx, "/protoapi.Storage/GetMemeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	AddMeme(context.Context, *AddMemeRequest) (*empty.Empty, error)
	MakeAction(context.Context, *MakeActionRequest) (*empty.Empty, error)
	IsMemeExists(context.Context, *IsMemeExistsRequest) (*IsMemeExistsResponse, error)
	GetMemeById(context.Context, *GetMemeByIdRequest) (*GetMemeByIdResponse, error)
	MarkMemeShown(context.Context, *MarkMemeShownRequest) (*empty.Empty, error)
	GetMemes(context.Context, *GetMemesStorageRequest) (*GetMemesResponse, error)
	GetMemesUnshown(context.Context, *GetMemesStorageUnshownRequest) (*GetMemesResponse, error)
	GetShownMemesInfo(context.Context, *GetShownMemesInfoRequest) (*GetShownMemesInfoResponse, error)
	GetMemeInfo(context.Context, *GetMemeInfoRequest) (*GetMemeInfoResponse, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_AddMeme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).AddMeme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/AddMeme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).AddMeme(ctx, req.(*AddMemeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_MakeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).MakeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/MakeAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).MakeAction(ctx, req.(*MakeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_IsMemeExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMemeExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).IsMemeExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/IsMemeExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).IsMemeExists(ctx, req.(*IsMemeExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetMemeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetMemeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/GetMemeById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetMemeById(ctx, req.(*GetMemeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_MarkMemeShown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkMemeShownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).MarkMemeShown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/MarkMemeShown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).MarkMemeShown(ctx, req.(*MarkMemeShownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetMemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemesStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetMemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/GetMemes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetMemes(ctx, req.(*GetMemesStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetMemesUnshown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemesStorageUnshownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetMemesUnshown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/GetMemesUnshown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetMemesUnshown(ctx, req.(*GetMemesStorageUnshownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetShownMemesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShownMemesInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetShownMemesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/GetShownMemesInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetShownMemesInfo(ctx, req.(*GetShownMemesInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetMemeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetMemeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoapi.Storage/GetMemeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetMemeInfo(ctx, req.(*GetMemeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoapi.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMeme",
			Handler:    _Storage_AddMeme_Handler,
		},
		{
			MethodName: "MakeAction",
			Handler:    _Storage_MakeAction_Handler,
		},
		{
			MethodName: "IsMemeExists",
			Handler:    _Storage_IsMemeExists_Handler,
		},
		{
			MethodName: "GetMemeById",
			Handler:    _Storage_GetMemeById_Handler,
		},
		{
			MethodName: "MarkMemeShown",
			Handler:    _Storage_MarkMemeShown_Handler,
		},
		{
			MethodName: "GetMemes",
			Handler:    _Storage_GetMemes_Handler,
		},
		{
			MethodName: "GetMemesUnshown",
			Handler:    _Storage_GetMemesUnshown_Handler,
		},
		{
			MethodName: "GetShownMemesInfo",
			Handler:    _Storage_GetShownMemesInfo_Handler,
		},
		{
			MethodName: "GetMemeInfo",
			Handler:    _Storage_GetMemeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Meme.proto",
}
